### PR TITLE
update pr template file names

### PR DESCRIPTION
**Pull request by seantokuzo**
### Description

dev branch currently includes files `pull_request_template.md` and `PULL_REQUEST_TEMPLATE.md` causing issues for case-insensitive file systems (eg. Mac APFS) when pulling dev branch.

this 'first of 2' tickets renames these files to `pull_request_template_new.md` and `PULL_REQUEST_TEMPLATE_OLD.md`, respectively.

After merging to dev - a 2nd ticket will rename `pull_request_template_new.md` to `pull_request_template.md` and delete `PULL_REQUEST_TEMPLATE_OLD.md`. _In theory_ this will fix the current name casing bug and leave one PR template doc...

### Jira Task

[Jira Ticket](https://codehammers.atlassian.net/browse/CHE-165?atlOrigin=eyJpIjoiM2IzZTA2N2I3NjI0NDlmMzg4Y2QzOTI1ZDEzMjBmZTAiLCJwIjoiaiJ9)

### Testing Instructions

N/A

#### All Team Members

- [x] I added a descriptive title to this PR.
- [x] I filled out the **Description**, **Jira Task**, and **Testing Instructions** sections above.
- [ ] I added or updated [Jest unit tests]for any changes to components, server-side controllers, etc.
- [ ] I ran `npm run docker-test` in my local environment to check that this PR passes all unit tests.
- [ ] I did a quick check to make sure my code changes follow the recomended style guide.

### CODE REVIEW

**Review by jimpulsee — APPROVED** [review]
Do we need the 'old' template? Can it not be removed, or simply edited and then committed as a change?

**Comment by seantokuzo** [comment]
> Do we need the 'old' template? Can it not be removed, or simply edited and then committed as a change?

When I pull from dev only one of the files shows in my rootDir (bc of the case insensitivity os APFS on my mac) while the other shows in my git working directory:
Screenshot 2024-05-31 at 12 36 15 PM



I figured renaming both might be the safer bet - reason being... it felt right?

**Review by serenahromano — APPROVED** [review]
approved!

**Review by brok3turtl3 — APPROVED** [review]
50/50

**Pull request merged**
